name: Discord Weekly Registration

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  test-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "Scheduled workflow is running"
          date
